services:
  app:
    build: ./app
    ports:
    - "6969:6969"
    depends_on:
    - db
    restart: always

  db:
    image: mysql:5.7
    ports:
    - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

    volumes:
      - $PWD/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - $PWD/data:/var/lib/mysql
    restart: always