version: '3.8'
services:
  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    expose:
      - "8000"

  frontend:
    build: ./frontend
    environment:
      BACKEND_URL: http://backend:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend

  redis:
    expose:
      - "6379"
    image: redis:latest

volumes:
  db_data:
