version: '3.8'
services:
  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      DB_HOST: db
      DB_PORT: 5432
      MIN_WEIGHT: ${MIN_WEIGHT:-10}
      MAX_WEIGHT: ${MAX_WEIGHT:-650}
      MIN_HEIGHT: ${MIN_HEIGHT:-100}
      MAX_HEIGHT: ${MAX_HEIGHT:-250}
      MIN_AGE: ${MIN_AGE:-10}
      MAX_AGE: ${MAX_AGE:-150}
    depends_on:
      - db
    expose:
      - "8000"

  frontend:
    build: ./frontend
    environment:
      BACKEND_URL: http://backend:8000
      NEXT_PUBLIC_MIN_WEIGHT: ${MIN_WEIGHT:-10}
      NEXT_PUBLIC_MAX_WEIGHT: ${MAX_WEIGHT:-650}
      NEXT_PUBLIC_MIN_HEIGHT: ${MIN_HEIGHT:-100}
      NEXT_PUBLIC_MAX_HEIGHT: ${MAX_HEIGHT:-250}
      NEXT_PUBLIC_MIN_AGE: ${MIN_AGE:-10}
      NEXT_PUBLIC_MAX_AGE: ${MAX_AGE:-150}
    ports:
      - "3000:3000"
    depends_on:
      - backend

  redis:
    expose:
      - "6379"
    image: redis:latest

volumes:
  db_data:
