version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: baptender
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@db/baptender
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_USER: postgres
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    environment:
      BACKEND_URL: http://backend:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend

  redis:
    ports:
      - "6379:6379"
    image: redis:latest

volumes:
  db_data:
