FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY api ./api
COPY db ./db
COPY scripts ./scripts
RUN chmod +x ./scripts/start.sh
EXPOSE 8000
CMD ["./scripts/start.sh"]

