CREATE DATABASE main;
USE main;

CREATE TABLE users (
    User VARCHAR(50) PRIMARY KEY NOT NULL,
    Weight FLOAT NOT NULL,
    Gender VARCHAR(6) NOT NULL
);

CREATE TABLE drinks (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    User VARCHAR(50) NOT NULL,
    Time DATETIME DEFAULT CURRENT_TIMESTAMP,
    Volume FLOAT NOT NULL,
    Strength FLOAT NOT NULL,
    FOREIGN KEY (User) REFERENCES users(User)
);
